import Head from "next/head";

import localFont from "next/font/local";

const imbVgaFont = localFont({ src: "../../public/fonts/imb_vga.woff" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kuba JJIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${imbVgaFont.className}`}>
        <div>
          <p>yo</p>
        </div>
      </main>
    </>
  );
}
