import { FC } from "react";
import Head from "next/head";
import localFont from "next/font/local";
import { Typography } from "@mui/material";

import Wrapper from "@/common/components/Wrapper";
import theme from "@/styles/theme";
import PokemonForm from "@/modules/pokemonForm";

export const imbVgaFont = localFont({ src: "../../public/fonts/imb_vga.woff" });

interface MyDate {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  seconds: number;
  milliSeconds: number;
  dateTime: string;
  date: string;
  time: string;
  timeZone: string;
  dayOfWeek: string;
  dstActive: boolean;
}

export async function getServerSideProps() {
  try {
    const res = await fetch(
      "https://www.timeapi.io/api/Time/current/zone?timeZone=Europe/Warsaw",
    );
    const date = await res.json();

    return { props: { date } };
  } catch {
    return {
      props: {
        year: 1994,
        month: 10,
        day: 1,
        hour: 12,
        minute: 12,
        seconds: 12,
        milliSeconds: 12,
        dateTime: "122",
        date: "12",
        time: "12",
        timeZone: "gmt+1",
        dayOfWeek: "Wednesday",
        dstActive: true,
      },
    };
  }
}

const Home: FC<{ date: MyDate }> = ({ date }) => {
  const dateToDisplay = `${date.dayOfWeek}, ${date.day}.${date.month}.${date.year}`;

  return (
    <>
      <Head>
        <title>Kuba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={imbVgaFont.className}>
        <Wrapper>
          <Typography
            align="right"
            fontSize="12px"
            color={theme.palette.grey_.grey_100}
          >
            {dateToDisplay}
          </Typography>
          <PokemonForm />
        </Wrapper>
      </main>
    </>
  );
};

export default Home;
