import { FC } from "react";
import Head from "next/head";
import localFont from "next/font/local";
import { Typography } from "@mui/material";

import Wrapper from "@/common/components/Wrapper";
import Button from "@/common/components/Button";
import theme from "@/styles/theme";

export const imbVgaFont = localFont({ src: "../../public/fonts/imb_vga.woff" });

interface MyDate {
  year: number;
  month: number;
  day: number;
  hour: number;
  minute: number;
  seconds: number;
  milliSeconds: number;
  dateTime: string;
  date: string;
  time: string;
  timeZone: string;
  dayOfWeek: string;
  dstActive: boolean;
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://www.timeapi.io/api/Time/current/zone?timeZone=Europe/Warsaw",
  );
  const date = await res.json();

  return { props: { date } };
}

const Home: FC<{ date: MyDate }> = ({ date }) => {
  const dateToDisplay = `${date.dayOfWeek}, ${date.day}.${date.month}.${date.year}`;

  return (
    <>
      <Head>
        <title>Kuba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={imbVgaFont.className}>
        <Wrapper>
          <Typography
            align="right"
            fontSize="12px"
            color={theme.palette.grey_.grey_100}
          >
            {dateToDisplay}
          </Typography>
        </Wrapper>
      </main>
    </>
  );
};

export default Home;
